/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Signer,
  utils,
  Contract,
  ContractFactory,
  BigNumberish,
  Overrides,
} from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type {
  StartTokenIdHelper,
  StartTokenIdHelperInterface,
} from "../../../contracts/mocks/StartTokenIdHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "startTokenId_",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "startTokenId",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506040516100db3803806100db83398101604081905261002f91610037565b600055610050565b60006020828403121561004957600080fd5b5051919050565b607d8061005e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063e6798baa14602d575b600080fd5b603560005481565b60405190815260200160405180910390f3fea2646970667358221220ad1a958ac704b4fa80222a6d09fdb9e530b278071775cefb445ac96ec27e37cb64736f6c63430008090033";

type StartTokenIdHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: StartTokenIdHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class StartTokenIdHelper__factory extends ContractFactory {
  constructor(...args: StartTokenIdHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    startTokenId_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<StartTokenIdHelper> {
    return super.deploy(
      startTokenId_,
      overrides || {}
    ) as Promise<StartTokenIdHelper>;
  }
  override getDeployTransaction(
    startTokenId_: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(startTokenId_, overrides || {});
  }
  override attach(address: string): StartTokenIdHelper {
    return super.attach(address) as StartTokenIdHelper;
  }
  override connect(signer: Signer): StartTokenIdHelper__factory {
    return super.connect(signer) as StartTokenIdHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StartTokenIdHelperInterface {
    return new utils.Interface(_abi) as StartTokenIdHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StartTokenIdHelper {
    return new Contract(address, _abi, signerOrProvider) as StartTokenIdHelper;
  }
}
