/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as extensions from "./extensions";
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export * as proxies from "./proxies";
export * as utils from "./utils";
export { Akwukwo__factory } from "./Akwukwo__factory";
export { INN__factory } from "./INN__factory";
export { Nnata__factory } from "./Nnata__factory";
export { Onuahia__factory } from "./Onuahia__factory";
