/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as extensions from "./extensions";
export type { extensions };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as mocks from "./mocks";
export type { mocks };
import type * as proxies from "./proxies";
export type { proxies };
import type * as utils from "./utils";
export type { utils };
export type { Akwukwo } from "./Akwukwo";
export type { INN } from "./INN";
export type { Nnata } from "./Nnata";
export type { Onuahia } from "./Onuahia";
