/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AuthProxy__factory } from "./AuthProxy__factory";
export { SendValue__factory } from "./SendValue__factory";
